### ISSUE TITLE
create digest fails with large query

### ISSUE THREAD

**Issue by lonnylundsten** [kevinsbarnard/m3-download#6]
Running the following command results in the error below. I presume this is because the query is too big?
Can we investigate this?

**python generate_digest.py -a 'Nanomia bijuga'**

Getting observations for Nanomia bijuga...
Traceback (most recent call last):
  File "/Users/lonny/Documents/Code/Python/4_m3-download/generate_digest.py", line 125, in <module>
    main(args.concept, args.config, args.descendants, args.all)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/generate_digest.py", line 41, in main
    json_data = get_fast_concept_images(config, concept)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/lib/m3_requests.py", line 11, in get_fast_concept_images
    return requests.get(config('m3', 'fastconceptimages') + '/' + concept).json()
  File "/Users/lonny/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/lonny/.pyenv/versions/3.9.5/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/lonny/.pyenv/versions/3.9.5/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/lonny/.pyenv/versions/3.9.5/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lonnylundsten** [comment]
If this is in fact related to query size, perhaps we can just limit the query to 1000 images or something? I would prefer not to do that but perhaps to get this working quickly a flag could be added to limit the number queried for.

**Comment by kevinsbarnard** [comment]
This looks like an endpoint bug perhaps unrelated to the size of the query- I'll let Brian know. for 'Nanomia bijuga', m3-download does a GET request to http://m3.shore.mbari.org/anno/v1/fast/concept/images/Nanomia%20bijuga which throws an error.

**Comment by lonnylundsten** [comment]
Looks like the endpoints are fixed and the code is working now for these bigger queries.

**Comment by lonnylundsten** [comment]
I spoke too soon. Now the generate_digest code is failing with the following error:

python generate_digest.py -a 'Nanomia bijuga'

Getting observations for Nanomia bijuga...
Found 3233 observations of Nanomia bijuga with valid images
Fetching all other observations for 2753 imaged moments...
Traceback (most recent call last):   (118/2753)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/generate_digest.py", line 125, in <module>
    main(args.concept, args.config, args.descendants, args.all)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/generate_digest.py", line 82, in main
    'observation_timestamp': observation['observation_timestamp'],
KeyError: 'observation_timestamp'

**Comment by lonnylundsten** [comment]
Things have been working pretty well but when I attempt reformatting a very large image set, _Calycophorae -d_, I'm getting a new failure:

❯ python reformat.py -o ~/Desktop/midwater/Calycophorae/ -f VOC --image_map /Users/lonny/Documents/Code/Python/4_m3-download/image_map.json /Users/lonny/Documents/Code/Python/4_m3-download/localizations.json
Traceback (most recent call last):
  File "/Users/lonny/Documents/Code/Python/4_m3-download/reformat.py", line 109, in <module>
    main(_args.localizations, _output, _args.format.upper(), _args.image_map)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/reformat.py", line 68, in main
    iruuid = loc['localization']['image_reference_uuid']
KeyError: 'image_reference_uuid'

**Comment by kevinsbarnard** [comment]
It looks like there were some localizations ingested into VARS from a generator 'gridview for files' which are malformed (missing the `image_reference_uuid` tag). Investigating now

**Comment by lonnylundsten** [comment]
Same thing is happening with Copepoda:

❯ python reformat.py -o ~/Desktop/midwater/Copepoda -f VOC --image_map /Users/lonny/Documents/Code/Python/4_m3-download/image_map.json /Users/lonny/Documents/Code/Python/4_m3-download/localizations.json
Traceback (most recent call last):
  File "/Users/lonny/Documents/Code/Python/4_m3-download/reformat.py", line 109, in <module>
    main(_args.localizations, _output, _args.format.upper(), _args.image_map)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/reformat.py", line 76, in main
    annotation_record.add_annotation(iruuid, locs, image_map)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/lib/localization.py", line 276, in add_annotation
    raise ValueError(f'No image found for image reference UUID {image_reference_uuid}')
ValueError: No image found for image reference UUID 46879d0f-16c8-4851-8548-f0d9b079cbbe

**Comment by kevinsbarnard** [comment]
I haven't been able to track down the source of the malformed localizations, but I added a check to `reformat.py` for any localizations with a missing image reference (necessary for back-referencing). You should now see a warning message such as 
```
[WARNING] Localization with association UUID a2d76d5a-377e-4bd3-5f67-09053b38bd1e has malformed JSON, skipping
```
when encountering these instances.

**Comment by lonnylundsten** [comment]
So will it skip these and allow me to process the rest?

**Comment by kevinsbarnard** [comment]
Yes, those localizations will be omitted from the reformatted annotations generated.
